//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\MSSQLLocalDB;Initial Catalog=Test_DataBase;Integrated Secur" +
            "ity=True")]
        public string Test_DataBaseConnectionString {
            get {
                return ((string)(this["Test_DataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLDEV\\DEVDBSQL;Initial Catalog=orgsys2017;Persist Security Info=" +
            "True;User ID=sa;Password=!Saturn42")]
        public string orgsys2017ConnectionString3 {
            get {
                return ((string)(this["orgsys2017ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLDEV\\DEVDBSQL;Initial Catalog=orgsys2017;Persist Security Info=" +
            "True;User ID=sa;Password=!Saturn42")]
        public string orgsys2017ConnectionString4 {
            get {
                return ((string)(this["orgsys2017ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=osi-svr104\\dev;Initial Catalog=orgsys2017;Persist Security Info=True;" +
            "User ID=sa;Password=!Saturn42")]
        public string orgsys2017ConnectionString {
            get {
                return ((string)(this["orgsys2017ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLPROD;Initial Catalog=orgsys2017;Persist Security Info=True;Use" +
            "r ID=sa;Password=!Saturn42")]
        public string orgsys2017ConnectionString1 {
            get {
                return ((string)(this["orgsys2017ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLDEV\\DEVDBSQL;Initial Catalog=orgsys2017;Persist Security Info=" +
            "True;User ID=sa;Password=!Saturn42")]
        public string orgsys2017ConnectionString2 {
            get {
                return ((string)(this["orgsys2017ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLDEV\\DEVDBSQL;Initial Catalog=orgsys2017;Persist Security Info=" +
            "True;User ID=sa;Password=!Saturn42")]
        public string OrgSysConnectionString_dev {
            get {
                return ((string)(this["OrgSysConnectionString_dev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLPROD;Initial Catalog=umbrella;Persist Security Info=True;User " +
            "ID=sa;Password=!Saturn42;MultipleActiveResultSets=True")]
        public string orgsys2017ConnectionString6 {
            get {
                return ((string)(this["orgsys2017ConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLDEV\\DEVDBSQL;Initial Catalog=orgsys2017;Persist Security Info=" +
            "True;User ID=sa;Password=!Saturn42;MultipleActiveResultSets=True")]
        public string umbrellaConnectionString {
            get {
                return ((string)(this["umbrellaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLDEV\\DEVDBSQL;Initial Catalog=orgsys2017;Persist Security Info=" +
            "True;User ID=sa;Password=!Saturn42")]
        public string DEVDB {
            get {
                return ((string)(this["DEVDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLPROD;Initial Catalog=umbrella;Persist Security Info=True;User " +
            "ID=sa;Password=!Saturn42")]
        public string PRODDB {
            get {
                return ((string)(this["PRODDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OSI-SQLDEV\\DEVDBSQL;Initial Catalog=orgsys2017;Integrated Security=Tr" +
            "ue")]
        public string orgsys2017ConnectionString5 {
            get {
                return ((string)(this["orgsys2017ConnectionString5"]));
            }
        }
    }
}
